import {
  AIAgent,
  AgentRole,
  PromptVersion,
  WorkforceJob,
  WorkQueueType,
  WorkforceMetricsSummary,
  JobStatus,
  AIModelProvider,
  ModelName,
} from '@/types/ai-workforce';

// ─── 29 SPECIALIZED AI EMPLOYEES REGISTRY ──────────────────────────────────
const AI_AGENTS_REGISTRY: AIAgent[] = [
  {
    id: 'agent-01',
    role: 'question_writer',
    displayName: 'BACB Question Writer',
    description: 'Generates high-quality BACB RBT 3rd Edition TCO practice questions with realistic clinical scenarios.',
    department: 'content',
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.7,
    maxTokens: 1200,
    promptVersion: 'v2.1',
    systemPrompt: 'You are an expert BACB Board Certified Behavior Analyst (BCBA) exam developer. Write clear, non-ambiguous practice questions adhering strictly to BACB Task List standards.',
    isActive: true,
    requiresHumanApproval: true,
    totalJobsProcessed: 142,
    successRatePercentage: 98.6,
    averageLatencyMs: 1850,
    totalCostUSD: 4.26,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-02',
    role: 'fact_checker',
    displayName: 'BACB Fact Checker',
    description: 'Verifies ABA theoretical accuracy, Ethics Code compliance, and Task List alignment.',
    department: 'quality',
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.1,
    maxTokens: 800,
    promptVersion: 'v1.5',
    systemPrompt: 'You are a senior ABA compliance officer. Verify every technical assertion against Cooper, Heron, & Heward (3rd ed) and the BACB Ethics Code.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 142,
    successRatePercentage: 99.3,
    averageLatencyMs: 920,
    totalCostUSD: 1.84,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-03',
    role: 'grammar_reviewer',
    displayName: 'Clinical Copyeditor',
    description: 'Ensures clear, concise, professional clinical phrasing with zero grammatical flaws.',
    department: 'quality',
    modelProvider: 'gemini',
    modelName: 'gemini-1.5-pro',
    temperature: 0.2,
    maxTokens: 600,
    promptVersion: 'v1.2',
    systemPrompt: 'You are an AP-style clinical copyeditor. Optimize syntax, clarity, tone, and formatting.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 140,
    successRatePercentage: 100,
    averageLatencyMs: 640,
    totalCostUSD: 0.98,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-04',
    role: 'seo_specialist',
    displayName: 'Programmatic SEO Specialist',
    description: 'Injects target ABA search keywords, title tags, and meta descriptions into generated content.',
    department: 'seo',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.4,
    maxTokens: 500,
    promptVersion: 'v2.0',
    systemPrompt: 'You are an organic SEO specialist for healthcare education. Optimize keyword placement, URL slugs, meta descriptions, and header hierarchy.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 110,
    successRatePercentage: 97.2,
    averageLatencyMs: 480,
    totalCostUSD: 0.44,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-05',
    role: 'content_reviewer',
    displayName: 'Chief Editorial Officer',
    description: 'Final quality Gatekeeper. Evaluates combined draft output before queuing for publication.',
    department: 'quality',
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.2,
    maxTokens: 800,
    promptVersion: 'v1.8',
    systemPrompt: 'You are the Chief Editorial Officer. Review the full content package and assign a PASS/FAIL score (0-100) with detailed approval notes.',
    isActive: true,
    requiresHumanApproval: true,
    totalJobsProcessed: 138,
    successRatePercentage: 96.4,
    averageLatencyMs: 1100,
    totalCostUSD: 2.15,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-06',
    role: 'ai_tutor',
    displayName: 'Socrates AI Tutor',
    description: 'Socratic mentor guiding candidates through complex ABA concepts.',
    department: 'learning',
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.6,
    maxTokens: 1000,
    promptVersion: 'v3.0',
    systemPrompt: 'You are Socrates, the lead AI Tutor for RBT Practice Questions. Use Socratic questioning to guide candidates to correct behavior-analytic reasoning.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 480,
    successRatePercentage: 99.1,
    averageLatencyMs: 1250,
    totalCostUSD: 14.40,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-07',
    role: 'flashcard_writer',
    displayName: 'Spaced Repetition Flashcard Author',
    description: 'Creates atomic front/back flashcards for key ABA terminology.',
    department: 'content',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.5,
    maxTokens: 600,
    promptVersion: 'v1.4',
    systemPrompt: 'Create atomic, single-concept flashcards optimized for Leitner box spaced repetition learning.',
    isActive: true,
    requiresHumanApproval: true,
    totalJobsProcessed: 95,
    successRatePercentage: 98.9,
    averageLatencyMs: 520,
    totalCostUSD: 0.38,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-08',
    role: 'scenario_writer',
    displayName: 'Clinical Scenario Writer',
    description: 'Drafts real-world ABA clinic scenarios involving pediatric clients, data collection, and behavior plans.',
    department: 'content',
    modelProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    temperature: 0.7,
    maxTokens: 1400,
    promptVersion: 'v1.1',
    systemPrompt: 'Draft realistic clinical ABA scenarios illustrating ethical, measurement, and intervention principles in practice.',
    isActive: true,
    requiresHumanApproval: true,
    totalJobsProcessed: 64,
    successRatePercentage: 96.8,
    averageLatencyMs: 2100,
    totalCostUSD: 3.20,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-09',
    role: 'glossary_writer',
    displayName: 'ABA Terminology Glossary Author',
    description: 'Generates comprehensive glossary definitions with clinical examples and non-examples.',
    department: 'content',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.3,
    maxTokens: 700,
    promptVersion: 'v1.0',
    systemPrompt: 'Write precise ABA glossary definitions with real-world clinical examples, non-examples, and BACB task list references.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 78,
    successRatePercentage: 100,
    averageLatencyMs: 490,
    totalCostUSD: 0.31,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-10',
    role: 'study_guide_writer',
    displayName: 'Comprehensive Study Guide Author',
    description: 'Compiles in-depth multi-section study guides for entire BACB Task List domains.',
    department: 'content',
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.5,
    maxTokens: 2500,
    promptVersion: 'v1.3',
    systemPrompt: 'Write comprehensive, structured study guides covering entire BACB Task List sections with visual ASCII diagrams and key takeaways.',
    isActive: true,
    requiresHumanApproval: true,
    totalJobsProcessed: 32,
    successRatePercentage: 93.7,
    averageLatencyMs: 3400,
    totalCostUSD: 4.80,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-11',
    role: 'internal_linking_expert',
    displayName: 'Internal Link Optimizer',
    description: 'Identifies semantic anchor text opportunities to link questions, glossary terms, and study guides.',
    department: 'seo',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.2,
    maxTokens: 400,
    promptVersion: 'v1.0',
    systemPrompt: 'Analyze content text and return JSON list of target internal links and anchor text insertions.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 88,
    successRatePercentage: 98.8,
    averageLatencyMs: 350,
    totalCostUSD: 0.17,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-12',
    role: 'metadata_writer',
    displayName: 'Meta & OpenGraph Writer',
    description: 'Generates SEO title tags, meta descriptions, and Twitter/OG card metadata.',
    department: 'seo',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.4,
    maxTokens: 300,
    promptVersion: 'v1.0',
    systemPrompt: 'Write click-worthy, SEO-optimized title tags (<60 chars) and meta descriptions (<155 chars).',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 120,
    successRatePercentage: 100,
    averageLatencyMs: 280,
    totalCostUSD: 0.12,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-13',
    role: 'schema_generator',
    displayName: 'JSON-LD Schema Architect',
    description: 'Generates structured JSON-LD schema markup (Quiz, Question, FAQPage, Course).',
    department: 'seo',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.1,
    maxTokens: 600,
    promptVersion: 'v1.1',
    systemPrompt: 'Output valid JSON-LD schema markup matching schema.org specifications for Educational / Quiz content.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 115,
    successRatePercentage: 100,
    averageLatencyMs: 310,
    totalCostUSD: 0.15,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-14',
    role: 'image_prompt_creator',
    displayName: 'Visual Asset Prompt Creator',
    description: 'Generates detailed prompts for generating educational UI diagrams and hero images.',
    department: 'content',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.7,
    maxTokens: 400,
    promptVersion: 'v1.0',
    systemPrompt: 'Generate vivid, non-device image prompts for educational ABA diagrams and infographics.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 45,
    successRatePercentage: 97.7,
    averageLatencyMs: 410,
    totalCostUSD: 0.09,
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-15',
    role: 'learning_coach',
    displayName: 'Behavioral Motivation Coach',
    description: 'Provides personalized encouragement, streak celebrations, and daily study advice.',
    department: 'learning',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.8,
    maxTokens: 500,
    promptVersion: 'v1.2',
    systemPrompt: 'You are an empathetic, highly supportive learning coach for candidates studying for high-stakes certification exams.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 210,
    successRatePercentage: 99.5,
    averageLatencyMs: 460,
    totalCostUSD: 0.42,
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-16',
    role: 'study_planner',
    displayName: 'Dynamic Schedule Planner',
    description: 'Constructs customized weekly study plans matching candidate target exam date and weak areas.',
    department: 'learning',
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.4,
    maxTokens: 1000,
    promptVersion: 'v2.0',
    systemPrompt: 'Generate customized day-by-day study calendars prioritizing candidate weak Task List categories.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 165,
    successRatePercentage: 98.1,
    averageLatencyMs: 1400,
    totalCostUSD: 3.30,
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-17',
    role: 'adaptive_learning_agent',
    displayName: 'Adaptive Recommendation Engine Agent',
    description: 'Selects optimal next questions and flashcards based on candidate response history.',
    department: 'learning',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.2,
    maxTokens: 500,
    promptVersion: 'v1.5',
    systemPrompt: 'Analyze candidate performance metrics and return next question IDs to target learning gaps.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 320,
    successRatePercentage: 99.7,
    averageLatencyMs: 390,
    totalCostUSD: 0.64,
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-18',
    role: 'weak_topic_analyzer',
    displayName: 'Task List Vulnerability Analyzer',
    description: 'Diagnoses specific BACB Task List weak areas from practice exam error logs.',
    department: 'learning',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.2,
    maxTokens: 600,
    promptVersion: 'v1.1',
    systemPrompt: 'Analyze test answer logs and output prioritized list of weak Task List sub-categories.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 195,
    successRatePercentage: 99.0,
    averageLatencyMs: 440,
    totalCostUSD: 0.39,
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-19',
    role: 'exam_readiness_coach',
    displayName: 'Exam Readiness Probability Assessor',
    description: 'Calculates candidate pass probability and readiness score (0-100%).',
    department: 'learning',
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.1,
    maxTokens: 500,
    promptVersion: 'v1.3',
    systemPrompt: 'Evaluate candidate score trends, accuracy by difficulty, and timing metrics to estimate pass probability.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 140,
    successRatePercentage: 98.5,
    averageLatencyMs: 980,
    totalCostUSD: 1.40,
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-20',
    role: 'analytics_assistant',
    displayName: 'BI Data Insights Assistant',
    description: 'Generates executive summaries of platform user growth, revenue, and content engagement.',
    department: 'operations',
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.3,
    maxTokens: 800,
    promptVersion: 'v1.0',
    systemPrompt: 'Synthesize platform raw analytics events into executive narrative summaries with bullet points.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 55,
    successRatePercentage: 100,
    averageLatencyMs: 1150,
    totalCostUSD: 0.88,
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-21',
    role: 'support_agent',
    displayName: 'Candidate Helpdesk Assistant',
    description: 'Handles candidate support inquiries regarding subscription plans, exam structure, and app features.',
    department: 'operations',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.5,
    maxTokens: 600,
    promptVersion: 'v1.2',
    systemPrompt: 'Answer user support questions politely and accurately using approved platform knowledge sources.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 280,
    successRatePercentage: 99.2,
    averageLatencyMs: 420,
    totalCostUSD: 0.56,
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-22',
    role: 'billing_assistant',
    displayName: 'SaaS Billing & Plan Concierge',
    description: 'Assists candidates and clinic admins with subscription upgrades, invoices, and coupon codes.',
    department: 'operations',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.2,
    maxTokens: 500,
    promptVersion: 'v1.0',
    systemPrompt: 'Assist users with billing questions, subscription plan differences, and receipt requests.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 90,
    successRatePercentage: 98.8,
    averageLatencyMs: 380,
    totalCostUSD: 0.18,
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-23',
    role: 'admin_assistant',
    displayName: 'Super Admin Workflow Assistant',
    description: 'Executes administrative tasks like bulk question status updates and user permission checks.',
    department: 'operations',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.1,
    maxTokens: 400,
    promptVersion: 'v1.0',
    systemPrompt: 'Assist administrators with platform operations and settings changes.',
    isActive: true,
    requiresHumanApproval: true,
    totalJobsProcessed: 40,
    successRatePercentage: 100,
    averageLatencyMs: 330,
    totalCostUSD: 0.08,
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-24',
    role: 'notification_assistant',
    displayName: 'Engagement Notification Copywriter',
    description: 'Drafts engaging push notifications, email subjects, and in-app reminder messages.',
    department: 'operations',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.7,
    maxTokens: 400,
    promptVersion: 'v1.1',
    systemPrompt: 'Draft high-converting, friendly push notifications and email subjects for candidate study reminders.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 150,
    successRatePercentage: 99.3,
    averageLatencyMs: 360,
    totalCostUSD: 0.30,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-25',
    role: 'translation_agent',
    displayName: 'Multilingual ABA Translator',
    description: 'Translates practice questions and flashcards into Spanish and Portuguese while preserving technical ABA terms.',
    department: 'content',
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.3,
    maxTokens: 1200,
    promptVersion: 'v1.0',
    systemPrompt: 'Translate technical ABA content preserving official BACB Spanish/Portuguese term equivalents.',
    isActive: true,
    requiresHumanApproval: true,
    totalJobsProcessed: 72,
    successRatePercentage: 97.2,
    averageLatencyMs: 1600,
    totalCostUSD: 1.44,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-26',
    role: 'knowledge_curator',
    displayName: 'RAG Knowledge Ingestion Curator',
    description: 'Cleans, formats, and tags incoming study resources for ingestion into the RAG vector store.',
    department: 'technical',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.1,
    maxTokens: 800,
    promptVersion: 'v1.2',
    systemPrompt: 'Format and extract structured keywords/metadata from study documents for vector database indexing.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 110,
    successRatePercentage: 100,
    averageLatencyMs: 480,
    totalCostUSD: 0.22,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-27',
    role: 'prompt_engineer',
    displayName: 'Meta Prompt Optimization Agent',
    description: 'Evaluates agent performance logs and suggests improved system prompt versions.',
    department: 'technical',
    modelProvider: 'openai',
    modelName: 'gpt-4o',
    temperature: 0.4,
    maxTokens: 1000,
    promptVersion: 'v1.0',
    systemPrompt: 'Analyze system prompt performance logs and write optimized system prompt iterations.',
    isActive: true,
    requiresHumanApproval: true,
    totalJobsProcessed: 28,
    successRatePercentage: 96.4,
    averageLatencyMs: 1800,
    totalCostUSD: 0.56,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-28',
    role: 'rag_optimizer',
    displayName: 'Hybrid Vector Search Optimizer',
    description: 'Tunes top-K and similarity score thresholds for hybrid RAG search queries.',
    department: 'technical',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.2,
    maxTokens: 500,
    promptVersion: 'v1.0',
    systemPrompt: 'Analyze RAG retrieval confidence scores and tune topK and similarity weighting factors.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 35,
    successRatePercentage: 100,
    averageLatencyMs: 400,
    totalCostUSD: 0.07,
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'agent-29',
    role: 'qa_agent',
    displayName: 'Quality Assurance Testing Agent',
    description: 'Validates API responses and UI component states against predefined test assertions.',
    department: 'quality',
    modelProvider: 'openai',
    modelName: 'gpt-4o-mini',
    temperature: 0.1,
    maxTokens: 600,
    promptVersion: 'v1.0',
    systemPrompt: 'Verify API JSON responses match required TypeScript schemas and contain non-null fields.',
    isActive: true,
    requiresHumanApproval: false,
    totalJobsProcessed: 160,
    successRatePercentage: 99.4,
    averageLatencyMs: 370,
    totalCostUSD: 0.32,
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
];

// In-Memory Job Queue Store (Supabase ready)
const WORKFORCE_JOBS: WorkforceJob[] = [
  {
    id: 'job-101',
    queueType: 'content_queue',
    primaryAgentRole: 'question_writer',
    pipelineRoles: ['question_writer', 'fact_checker', 'grammar_reviewer', 'seo_specialist', 'content_reviewer'],
    currentStepIndex: 4,
    payload: { category: 'Behavior Reduction', taskListCode: 'B-01', targetCertification: 'RBT' },
    stepResults: [
      { agentRole: 'question_writer', output: 'Drafted question on DRO procedure', score: 92, approved: true, latencyMs: 1800, tokensUsed: 420, costUSD: 0.012, timestamp: '2026-08-06T10:00:00Z' },
      { agentRole: 'fact_checker', output: 'Verified against Cooper 3rd ed B-01', score: 98, approved: true, latencyMs: 850, tokensUsed: 210, costUSD: 0.006, timestamp: '2026-08-06T10:01:00Z' },
      { agentRole: 'grammar_reviewer', output: 'Refined question stem formatting', score: 100, approved: true, latencyMs: 600, tokensUsed: 150, costUSD: 0.003, timestamp: '2026-08-06T10:01:30Z' },
      { agentRole: 'seo_specialist', output: 'Added slug rbt-dro-differential-reinforcement', score: 95, approved: true, latencyMs: 450, tokensUsed: 120, costUSD: 0.002, timestamp: '2026-08-06T10:02:00Z' },
      { agentRole: 'content_reviewer', output: 'Ready for human admin approval', score: 96, approved: true, latencyMs: 1050, tokensUsed: 300, costUSD: 0.009, timestamp: '2026-08-06T10:02:30Z' },
    ],
    finalOutput: 'Drafted question package ready for review.',
    status: 'in_review',
    createdAt: '2026-08-06T10:00:00Z',
  },
];

// ─── PUBLIC ENGINE API ───────────────────────────────────────────────────────

/**
 * Returns list of all 29 AI Agents
 */
export function getAllAIAgents(): AIAgent[] {
  return [...AI_AGENTS_REGISTRY];
}

/**
 * Get agent by role
 */
export function getAgentByRole(role: AgentRole): AIAgent | undefined {
  return AI_AGENTS_REGISTRY.find((a) => a.role === role);
}

/**
 * Multi-Agent Collaborative Execution Pipeline
 * Executes sequential step pipeline: e.g. Question Writer → Fact Checker → Grammar → SEO → Reviewer
 */
export function executeOrchestrationPipeline(
  pipelineRoles: AgentRole[],
  payload: Record<string, any>,
  queueType: WorkQueueType = 'content_queue'
): WorkforceJob {
  const jobId = `job-${Date.now()}`;
  const stepResults: WorkforceJob['stepResults'] = [];

  let currentPayload = { ...payload };

  pipelineRoles.forEach((role, idx) => {
    const agent = getAgentByRole(role);
    if (!agent || !agent.isActive) return;

    // Simulate agent execution step
    const latency = agent.averageLatencyMs + Math.floor(Math.random() * 200 - 100);
    const tokens = 200 + idx * 80;
    const cost = (tokens / 1000) * 0.002;

    const mockOutput = `[${agent.displayName}] Step ${idx + 1}/${pipelineRoles.length} completed for category: ${payload.category || 'General'}`;

    stepResults.push({
      agentRole: role,
      output: mockOutput,
      score: 90 + Math.floor(Math.random() * 10),
      approved: true,
      latencyMs: latency,
      tokensUsed: tokens,
      costUSD: parseFloat(cost.toFixed(4)),
      timestamp: new Date().toISOString(),
    });

    currentPayload[`step_${role}`] = mockOutput;
  });

  const requiresApproval = pipelineRoles.some((r) => getAgentByRole(r)?.requiresHumanApproval);

  const job: WorkforceJob = {
    id: jobId,
    queueType,
    primaryAgentRole: pipelineRoles[0] || 'question_writer',
    pipelineRoles,
    currentStepIndex: pipelineRoles.length - 1,
    payload,
    stepResults,
    finalOutput: `Pipeline completed across ${pipelineRoles.length} agents. Status: ${requiresApproval ? 'In Approval Queue' : 'Completed'}.`,
    status: requiresApproval ? 'in_review' : 'completed',
    createdAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
  };

  WORKFORCE_JOBS.unshift(job);
  return job;
}

/**
 * Returns workforce metrics summary for Admin Dashboard
 */
export function getWorkforceMetricsSummary(): WorkforceMetricsSummary {
  const agents = getAllAIAgents();
  const activeCount = agents.filter((a) => a.isActive).length;
  const totalCost = agents.reduce((sum, a) => sum + a.totalCostUSD, 0);

  return {
    totalAgents: agents.length,
    activeAgentsCount: activeCount,
    pendingJobsInQueue: WORKFORCE_JOBS.filter((j) => j.status === 'pending' || j.status === 'in_review').length,
    completedJobsToday: WORKFORCE_JOBS.filter((j) => j.status === 'completed').length + 18,
    overallSuccessRatePercentage: 98.8,
    totalTokenUsage24h: 145200,
    totalCost24hUSD: parseFloat(totalCost.toFixed(2)),
  };
}

/**
 * Update Model Routing for an Agent
 */
export function updateAgentModelRouting(
  role: AgentRole,
  modelProvider: AIModelProvider,
  modelName: ModelName
): AIAgent | undefined {
  const agent = AI_AGENTS_REGISTRY.find((a) => a.role === role);
  if (agent) {
    agent.modelProvider = modelProvider;
    agent.modelName = modelName;
    agent.updatedAt = new Date().toISOString();
  }
  return agent;
}

/**
 * Get all active workforce jobs
 */
export function getWorkforceJobs(): WorkforceJob[] {
  return [...WORKFORCE_JOBS];
}
