import { BACBDomain } from '@/types/bacb';

export const BACB_TASK_LIST_2ND_EDITION: BACBDomain[] = [
  {
    id: 'A',
    name: 'Measurement',
    shortName: 'Measurement',
    description: 'Prepare for data collection, implement continuous and discontinuous measurement procedures, and enter data into graphs.',
    iconName: 'BarChart3',
    questionCountApprox: 12,
    weightPercentage: 14,
    items: [
      {
        id: 'A-01',
        domainId: 'A',
        title: 'Prepare for data collection',
        description: 'Read session plans, gather necessary materials (timer, clicker, data sheets), and minimize distractions before client arrival.',
        keyConcepts: ['Session preparation', 'Target behavior definition', 'Measurement tools'],
        examWeightPercentage: 2.5,
      },
      {
        id: 'A-02',
        domainId: 'A',
        title: 'Implement continuous measurement procedures',
        description: 'Record every instance of target behavior during the observation period (Frequency/Count, Rate, Duration, Latency, IRT).',
        keyConcepts: ['Frequency', 'Rate', 'Duration', 'Latency', 'Inter-Response Time (IRT)'],
        examWeightPercentage: 3.5,
      },
      {
        id: 'A-03',
        domainId: 'A',
        title: 'Implement discontinuous measurement procedures',
        description: 'Record instances during specific interval samples (Partial Interval, Whole Interval, Momentary Time Sampling).',
        keyConcepts: ['Partial Interval (overestimates)', 'Whole Interval (underestimates)', 'Momentary Time Sampling'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'A-04',
        domainId: 'A',
        title: 'Implement permanent-product recording procedures',
        description: 'Measure the tangible environmental outcome or physical product resulting from a behavior (e.g., completed worksheets, clean room).',
        keyConcepts: ['Permanent Product', 'Tangible Outcome', 'No direct observation required'],
        examWeightPercentage: 2.0,
      },
      {
        id: 'A-05',
        domainId: 'A',
        title: 'Enter data and update graphs',
        description: 'Plot collected data accurately on line graphs or scatterplots following AB design or daily tracking standards.',
        keyConcepts: ['X-axis (Time/Sessions)', 'Y-axis (Target behavior)', 'Phase change lines'],
        examWeightPercentage: 1.5,
      },
      {
        id: 'A-06',
        domainId: 'A',
        title: 'Describe behavior and environment in observable and measurable terms',
        description: 'Formulate operational definitions focusing on topography and intensity without hypothetical construct language.',
        keyConcepts: ['Operational definition', 'Topography', 'Measurable terms', 'Non-judgmental language'],
        examWeightPercentage: 1.5,
      },
    ],
  },
  {
    id: 'B',
    name: 'Assessment',
    shortName: 'Assessment',
    description: 'Assist BCBA supervisors with preference assessments, functional assessments, and skill baseline data collection.',
    iconName: 'ClipboardCheck',
    questionCountApprox: 10,
    weightPercentage: 12,
    items: [
      {
        id: 'B-01',
        domainId: 'B',
        title: 'Conduct preference assessments',
        description: 'Identify potential motivators using Single Item, Paired Choice (Forced Choice), MSWO (Multiple Stimulus Without Replacement), or Free Operant methods.',
        keyConcepts: ['Free Operant', 'Paired Choice', 'MSWO', 'MSW'],
        examWeightPercentage: 3.5,
      },
      {
        id: 'B-02',
        domainId: 'B',
        title: 'Assist with individualized assessment procedures',
        description: 'Collect baseline data, probe skills, and support BCBAs during VB-MAPP, ABLLS-R, or AFLS assessments.',
        keyConcepts: ['Baseline data', 'Skill probing', 'Curriculum-based assessments'],
        examWeightPercentage: 2.5,
      },
      {
        id: 'B-03',
        domainId: 'B',
        title: 'Assist with functional assessment procedures',
        description: 'Record ABC data (Antecedent-Behavior-Consequence) during descriptive observations to determine potential behavior functions.',
        keyConcepts: ['ABC Data Collection', 'Direct Observation', '4 Functions (SEAT)'],
        examWeightPercentage: 3.0,
      },
    ],
  },
  {
    id: 'C',
    name: 'Skill Acquisition',
    shortName: 'Skill Acquisition',
    description: 'Implement written skill acquisition plans, discrete trial teaching, naturalistic teaching, task analysis, chaining, and prompt fading.',
    iconName: 'GraduationCap',
    questionCountApprox: 24,
    weightPercentage: 28,
    items: [
      {
        id: 'C-01',
        domainId: 'C',
        title: 'Identify essential components of a written skill acquisition plan',
        description: 'Understand target objective, criteria for mastery, prerequisite skills, materials, prompting strategies, and reinforcement schedule.',
        keyConcepts: ['Target skill', 'Mastery criterion', 'Reinforcement schedule', 'Prompt hierarchy'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'C-02',
        domainId: 'C',
        title: 'Prepare for the session as specified by the skill acquisition plan',
        description: 'Organize reinforcers, token boards, visual schedules, and target stimuli before beginning teaching trials.',
        keyConcepts: ['Trial preparation', 'Token boards', 'Visual cues'],
        examWeightPercentage: 2.0,
      },
      {
        id: 'C-03',
        domainId: 'C',
        title: 'Use contingencies of reinforcement',
        description: 'Deliver positive/negative reinforcement using continuous (CRF) or intermittent (VR, VI, FR, FI) schedules.',
        keyConcepts: ['Conditioned vs Unconditioned Reinforcers', 'Continuous vs Intermittent', 'Fixed vs Variable'],
        examWeightPercentage: 4.5,
      },
      {
        id: 'C-04',
        domainId: 'C',
        title: 'Implement Discrete Trial Teaching (DTT) procedures',
        description: 'Deliver clear Discriminative Stimulus (SD), provide prompt if needed, record response, deliver consequence, and manage inter-trial interval.',
        keyConcepts: ['SD -> Response -> Consequence', 'Inter-trial interval', 'Clear articulation'],
        examWeightPercentage: 4.5,
      },
      {
        id: 'C-05',
        domainId: 'C',
        title: 'Implement Naturalistic Teaching Procedures (NET)',
        description: 'Capitalize on client motivation, embed learning targets into natural play, and utilize incidental teaching opportunities.',
        keyConcepts: ['Incidental Teaching', 'Mand Model', 'Capturing vs Contriving motivation'],
        examWeightPercentage: 3.5,
      },
      {
        id: 'C-06',
        domainId: 'C',
        title: 'Implement Task Analysis and Chaining procedures',
        description: 'Break complex skills into sub-steps; execute Forward Chaining, Backward Chaining, or Total Task Presentation.',
        keyConcepts: ['Forward Chaining', 'Backward Chaining', 'Total Task', 'Task Analysis breakdown'],
        examWeightPercentage: 3.5,
      },
      {
        id: 'C-07',
        domainId: 'C',
        title: 'Implement Discrimination Training',
        description: 'Teach client to respond differently to different stimuli (SD vs S-Delta) through differential reinforcement.',
        keyConcepts: ['SD (Reinforcement available)', 'S-Delta (No reinforcement)', 'Mass Trials vs Distractor Trials'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'C-08',
        domainId: 'C',
        title: 'Implement Stimulus Control Transfer procedures',
        description: 'Gradually fade prompts so the target behavior shifts from prompt control to the natural SD.',
        keyConcepts: ['Stimulus Fading', 'Prompt Fading', 'Transfer of Control'],
        examWeightPercentage: 2.0,
      },
      {
        id: 'C-09',
        domainId: 'C',
        title: 'Implement Prompt and Prompt Fading procedures',
        description: 'Utilize Most-to-Least or Least-to-Most prompting (Full Physical, Partial Physical, Model, Gestural, Verbal, Positional).',
        keyConcepts: ['Prompt Hierarchy', 'Most-to-Least', 'Least-to-Most', 'Time Delay'],
        examWeightPercentage: 2.0,
      },
    ],
  },
  {
    id: 'D',
    name: 'Behavior Reduction',
    shortName: 'Behavior Reduction',
    description: 'Implement behavior intervention plans (BIP), antecedent strategies, differential reinforcement (DRA, DRO, DRI, DRL), and extinction procedures.',
    iconName: 'ShieldAlert',
    questionCountApprox: 18,
    weightPercentage: 21,
    items: [
      {
        id: 'D-01',
        domainId: 'D',
        title: 'Identify essential components of a written behavior reduction plan',
        description: 'Identify operational definition, hypotheses function (SEAT), antecedent interventions, replacement behaviors, and consequence strategies.',
        keyConcepts: ['Behavior Intervention Plan (BIP)', 'Function of behavior', 'Replacement behavior'],
        examWeightPercentage: 3.5,
      },
      {
        id: 'D-02',
        domainId: 'D',
        title: 'Describe common functions of behavior (SEAT)',
        description: 'Understand Sensory/Automatic, Escape/Avoidance, Attention, and Tangible functions.',
        keyConcepts: ['Sensory (Automatic)', 'Escape', 'Attention', 'Tangible'],
        examWeightPercentage: 4.0,
      },
      {
        id: 'D-03',
        domainId: 'D',
        title: 'Implement antecedent interventions',
        description: 'Modify environment before behavior occurs: Non-Contingent Reinforcement (NCR), High-Probability Request Sequence, Choice Making, Task Modification.',
        keyConcepts: ['NCR', 'High-P Request Sequence', 'Environmental modification', 'Establishing Operation (EO)'],
        examWeightPercentage: 4.0,
      },
      {
        id: 'D-04',
        domainId: 'D',
        title: 'Implement Differential Reinforcement procedures',
        description: 'Apply DRO (Other), DRA (Alternative), DRI (Incompatible), and DRL (Low Rates) reinforcement schedules.',
        keyConcepts: ['DRO (Zero instances)', 'DRA (Alternative behavior)', 'DRI (Incompatible physical state)', 'DRL'],
        examWeightPercentage: 4.5,
      },
      {
        id: 'D-05',
        domainId: 'D',
        title: 'Implement Extinction procedures',
        description: 'Withhold reinforcement for previously reinforced behavior; manage extinction burst and spontaneous recovery safely.',
        keyConcepts: ['Extinction Burst', 'Spontaneous Recovery', 'Escape Extinction', 'Sensory Extinction'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'D-06',
        domainId: 'D',
        title: 'Implement Crisis/Emergency procedures',
        description: 'Follow BCBA and facility safety guidelines to prevent harm to self or others while prioritizing client dignity.',
        keyConcepts: ['Safety first', 'De-escalation', 'Restraint only per state/BIP guidelines', 'Incident reporting'],
        examWeightPercentage: 2.0,
      },
    ],
  },
  {
    id: 'E',
    name: 'Documentation & Reporting',
    shortName: 'Documentation',
    description: 'Generate objective session notes, communicate effectively with BCBA supervisors, and follow reporting compliance rules.',
    iconName: 'FileText',
    questionCountApprox: 10,
    weightPercentage: 12,
    items: [
      {
        id: 'E-01',
        domainId: 'E',
        title: 'Effectively communicate with supervisor',
        description: 'Maintain open, timely communication regarding client progress, clinical changes, or unexpected environmental factors.',
        keyConcepts: ['BCBA feedback', 'Timely communication', 'Clinical escalation'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'E-02',
        domainId: 'E',
        title: 'Actively seek clinical direction from supervisor',
        description: 'Recognize when client targets require clarification or modification and request direct supervision.',
        keyConcepts: ['Scope of practice', 'Requesting guidance', 'Supervision compliance'],
        examWeightPercentage: 2.5,
      },
      {
        id: 'E-03',
        domainId: 'E',
        title: 'Generate objective session notes',
        description: 'Write clear, non-subjective session summaries stating observable facts, data percentages, and client responses.',
        keyConcepts: ['Objective language', 'Fact-based summary', 'Data reference'],
        examWeightPercentage: 3.5,
      },
      {
        id: 'E-04',
        domainId: 'E',
        title: 'Comply with legal, regulatory, and workplace requirements',
        description: 'Adhere to HIPAA privacy rules, mandatory abuse reporting guidelines, and data retention standards.',
        keyConcepts: ['HIPAA compliance', 'Mandated Reporter obligations', 'Data storage security'],
        examWeightPercentage: 3.0,
      },
    ],
  },
  {
    id: 'F',
    name: 'Professional Conduct & Scope',
    shortName: 'Ethics & Conduct',
    description: 'Adhere to BACB Ethics Code for RBTs, maintain dual-relationship boundaries, and meet mandatory 5% monthly supervision requirements.',
    iconName: 'UserCheck',
    questionCountApprox: 11,
    weightPercentage: 13,
    items: [
      {
        id: 'F-01',
        domainId: 'F',
        title: 'Respond appropriately to feedback',
        description: 'Receive BCBA constructive supervision non-defensively and implement recommendations immediately.',
        keyConcepts: ['Professional growth', 'Non-defensive reception', 'Implementation of feedback'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'F-02',
        domainId: 'F',
        title: 'Maintain professional boundaries (Avoid dual relationships)',
        description: 'Do not accept gifts, social media requests, babysitting jobs, or personal friendships with client families.',
        keyConcepts: ['Dual relationships', 'Conflict of interest', 'Gift policy (<$10 or zero tolerance)'],
        examWeightPercentage: 4.0,
      },
      {
        id: 'F-03',
        domainId: 'F',
        title: 'Maintain client dignity',
        description: 'Treat clients with respect, provide age-appropriate materials, ensure privacy during personal care, and support independence.',
        keyConcepts: ['Client dignity', 'Age-appropriate interactions', 'Privacy during hygiene'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'F-04',
        domainId: 'F',
        title: 'Comply with BACB supervision requirements',
        description: 'Ensure at least 5% of monthly ABA service hours are directly supervised by a qualified BCBA/BCaBA across 2 face-to-face contacts.',
        keyConcepts: ['5% Monthly Supervision rule', '2 Face-to-Face meetings per month', 'Supervision logbook'],
        examWeightPercentage: 3.0,
      },
    ],
  },
];
