import { ExamDomain } from '@/types/certification';

/**
 * BACB BCBA 6th Edition Test Content Outline (TCO)
 * Sections: 1. Foundations (Domains A-D) | 2. Applications (Domains E-I)
 */
export const BCBA_TASK_LIST_6TH_EDITION: ExamDomain[] = [
  {
    id: 'A',
    name: 'Behaviorism and Philosophical Foundations',
    shortName: 'Philosophical Foundations',
    description: 'Understand the philosophical underpinnings of behavior analysis, radical behaviorism, determinism, selectionism, pragmatism, and the 7 dimensions of ABA.',
    iconName: 'Compass',
    questionCountApprox: 12,
    weightPercentage: 6,
    items: [
      {
        id: 'A.1',
        domainId: 'A',
        title: 'Identify the goals of behavior analysis as a science (description, prediction, control)',
        description: 'Distinguish among description, prediction, and control as the three levels of scientific understanding.',
        keyConcepts: ['Description', 'Prediction', 'Control', 'Scientific Understanding'],
        examWeightPercentage: 1.5,
      },
      {
        id: 'A.2',
        domainId: 'A',
        title: 'Explain the philosophical assumptions underlying the science of behavior analysis',
        description: 'Selectionism, determinism, empiricism, parsimony, pragmatism, and environmental explanations.',
        keyConcepts: ['Determinism', 'Empiricism', 'Parsimony', 'Pragmatism', 'Selectionism'],
        examWeightPercentage: 1.5,
      },
      {
        id: 'A.3',
        domainId: 'A',
        title: 'Describe and explain behavior from the perspective of radical behaviorism',
        description: 'Analyze private events as behavior within a natural science framework without mentalistic constructs.',
        keyConcepts: ['Radical Behaviorism', 'Private Events', 'Mentalism Rejection'],
        examWeightPercentage: 1.5,
      },
      {
        id: 'A.4',
        domainId: 'A',
        title: 'Distinguish among behaviorism, EAB, ABA, and professional practice guided by the science',
        description: 'Four branches of behavior analysis and their distinct contributions to theory, research, and application.',
        keyConcepts: ['Behaviorism', 'EAB', 'ABA', 'Practice Guided by Behavior Analysis'],
        examWeightPercentage: 1.5,
      },
      {
        id: 'A.5',
        domainId: 'A',
        title: 'Describe and define the 7 dimensions of applied behavior analysis (Baer, Wolf, & Risley, 1968)',
        description: 'Applied, Behavioral, Analytic, Technological, Conceptually Systematic, Effective, Generality (GET A CAB).',
        keyConcepts: ['Applied', 'Behavioral', 'Analytic', 'Technological', 'Conceptually Systematic', 'Effective', 'Generality'],
        examWeightPercentage: 1.5,
      },
    ],
  },
  {
    id: 'B',
    name: 'Concepts and Principles',
    shortName: 'Concepts & Principles',
    description: 'Master operant and respondent conditioning, reinforcement/punishment schedules, extinction, stimulus control, motivating operations, and verbal operants.',
    iconName: 'Brain',
    questionCountApprox: 45,
    weightPercentage: 24,
    items: [
      {
        id: 'B.1',
        domainId: 'B',
        title: 'Define and provide examples of behavior, response, and response class',
        description: 'Differentiate topographical vs functional response classes and environmental interactions.',
        keyConcepts: ['Behavior', 'Response', 'Response Class', 'Topography vs Function'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'B.2',
        domainId: 'B',
        title: 'Define and provide examples of stimulus and stimulus class',
        description: 'Stimulus classes based on formal, temporal, and functional dimensions.',
        keyConcepts: ['Stimulus', 'Stimulus Class', 'Feature vs Arbitrary'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'B.3',
        domainId: 'B',
        title: 'Define and provide examples of respondent and operant conditioning',
        description: 'Pavlovian stimulus-stimulus pairing vs Skinnerian response-consequence contingencies.',
        keyConcepts: ['Respondent Conditioning', 'Operant Conditioning', 'Conditioned Reflex'],
        examWeightPercentage: 3.5,
      },
      {
        id: 'B.4',
        domainId: 'B',
        title: 'Define and provide examples of positive and negative reinforcement contingencies',
        description: 'Stimulus addition/presentation vs removal/attenuation increasing future response frequency.',
        keyConcepts: ['Positive Reinforcement', 'Negative Reinforcement', 'Escape vs Avoidance'],
        examWeightPercentage: 3.5,
      },
      {
        id: 'B.5',
        domainId: 'B',
        title: 'Define and provide examples of schedules of reinforcement',
        description: 'Fixed/Variable Ratio and Interval schedules, matching law, and concurrent contingencies.',
        keyConcepts: ['FR', 'VR', 'FI', 'VI', 'Matching Law', 'Post-reinforcement pause'],
        examWeightPercentage: 4.0,
      },
      {
        id: 'B.6',
        domainId: 'B',
        title: 'Define and provide examples of positive and negative punishment contingencies',
        description: 'Consequences that decrease future probability of behavior.',
        keyConcepts: ['Positive Punishment', 'Negative Punishment', 'Response Cost', 'Time-out'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'B.7',
        domainId: 'B',
        title: 'Define and provide examples of automatic and socially mediated contingencies',
        description: 'Contingencies produced directly by response vs mediated by another person.',
        keyConcepts: ['Automatic Reinforcement', 'Socially Mediated', 'Sensory consequences'],
        examWeightPercentage: 2.0,
      },
      {
        id: 'B.8',
        domainId: 'B',
        title: 'Define and provide examples of unconditioned, conditioned, and generalized reinforcers/punishers',
        description: 'Phylogenic vs ontogenic reinforcing and punishing stimuli; token economies.',
        keyConcepts: ['Unconditioned Reinforcer', 'Conditioned Reinforcer', 'Generalized Conditioned Reinforcer'],
        examWeightPercentage: 2.0,
      },
      {
        id: 'B.9',
        domainId: 'B',
        title: 'Define and provide examples of operant extinction',
        description: 'Withholding reinforcement for previously reinforced response; extinction bursts and spontaneous recovery.',
        keyConcepts: ['Extinction Burst', 'Spontaneous Recovery', 'Resistance to Extinction'],
        examWeightPercentage: 2.5,
      },
      {
        id: 'B.10',
        domainId: 'B',
        title: 'Define and provide examples of stimulus control, stimulus generalization, and stimulus discrimination',
        description: 'Discriminative stimuli (SD), S-delta, discrimination training, and generalization gradients.',
        keyConcepts: ['Stimulus Control', 'SD vs S-Delta', 'Generalization Gradient'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'B.11',
        domainId: 'B',
        title: 'Define and provide examples of motivating operations (EO, AO, CMO-S, CMO-R, CMO-T)',
        description: 'Value-altering and behavior-altering effects; unconditioned and conditioned motivating operations.',
        keyConcepts: ['Establishing Operation', 'Abolishing Operation', 'CMO-S', 'CMO-R', 'CMO-T'],
        examWeightPercentage: 4.0,
      },
      {
        id: 'B.12',
        domainId: 'B',
        title: 'Define and provide examples of rule-governed behavior and contingency-shaped behavior',
        description: 'Instructional control without direct contact with contingencies vs history of reinforcement.',
        keyConcepts: ['Rule-Governed Behavior', 'Contingency-Shaped Behavior', 'Delayed Consequences'],
        examWeightPercentage: 2.0,
      },
      {
        id: 'B.13',
        domainId: 'B',
        title: 'Define and provide examples of the verbal operants (mand, tact, echoic, intraverbal, textual, transcription)',
        description: 'Skinner\'s functional analysis of verbal behavior and elementary verbal operants.',
        keyConcepts: ['Mand', 'Tact', 'Echoic', 'Intraverbal', 'Textual', 'Transcription', 'Point-to-point correspondence', 'Formal similarity'],
        examWeightPercentage: 3.5,
      },
    ],
  },
  {
    id: 'C',
    name: 'Measurement, Data Display, and Interpretation',
    shortName: 'Measurement & Data',
    description: 'Select, implement, and evaluate continuous and discontinuous measurement systems, interobserver agreement (IOA), and visual data analysis.',
    iconName: 'BarChart3',
    questionCountApprox: 21,
    weightPercentage: 11,
    items: [
      {
        id: 'C.1',
        domainId: 'C',
        title: 'Establish operational definitions of behavior',
        description: 'Formulate clear, objective, and complete operational definitions.',
        keyConcepts: ['Operational Definition', 'Topography', 'Function'],
        examWeightPercentage: 2.0,
      },
      {
        id: 'C.2',
        domainId: 'C',
        title: 'Select and implement continuous and discontinuous measurement procedures',
        description: 'Count, rate, duration, latency, IRT, partial interval, whole interval, momentary time sampling, and PLACHECK.',
        keyConcepts: ['Continuous Measurement', 'Discontinuous Measurement', 'Time Sampling'],
        examWeightPercentage: 3.5,
      },
      {
        id: 'C.3',
        domainId: 'C',
        title: 'Select and calculate interobserver agreement (IOA)',
        description: 'Total count, mean count per interval, exact count per interval, trial-by-trial, scored interval, and unscored interval IOA.',
        keyConcepts: ['Total Count IOA', 'Exact Count IOA', 'Scored Interval IOA', 'IOA Standards (80%+)'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'C.4',
        domainId: 'C',
        title: 'Evaluate data using visual analysis (level, trend, variability, bounce)',
        description: 'Interpret line graphs, cumulative records, and scatterplots across experimental conditions.',
        keyConcepts: ['Level', 'Trend', 'Variability', 'Cumulative Record', 'Phase Change Line'],
        examWeightPercentage: 2.5,
      },
    ],
  },
  {
    id: 'D',
    name: 'Experimental Design',
    shortName: 'Experimental Design',
    description: 'Design, interpret, and evaluate single-case experimental designs, internal and external validity, component and parametric analyses.',
    iconName: 'FlaskConical',
    questionCountApprox: 17,
    weightPercentage: 9,
    items: [
      {
        id: 'D.1',
        domainId: 'D',
        title: 'Distinguish between internal and external validity in single-case research',
        description: 'Threats to internal validity (history, maturation, instrumentation) and replication for external validity.',
        keyConcepts: ['Internal Validity', 'External Validity', 'Replication'],
        examWeightPercentage: 2.5,
      },
      {
        id: 'D.2',
        domainId: 'D',
        title: 'Select and implement reversal (ABAB) and withdrawal designs',
        description: 'Demonstrating functional relations; ethical considerations regarding irreversibility and dangerous behaviors.',
        keyConcepts: ['Reversal Design', 'Withdrawal Design', 'Irreversibility'],
        examWeightPercentage: 2.5,
      },
      {
        id: 'D.3',
        domainId: 'D',
        title: 'Select and implement multielement / alternating treatments designs',
        description: 'Rapid alternation of conditions to compare interventions; multi-treatment interference.',
        keyConcepts: ['Alternating Treatments Design', 'Multielement Design', 'Multi-treatment Interference'],
        examWeightPercentage: 2.5,
      },
      {
        id: 'D.4',
        domainId: 'D',
        title: 'Select and implement multiple baseline and changing criterion designs',
        description: 'Multiple baseline across settings, subjects, or behaviors; changing criterion step sizes and bidirectionality.',
        keyConcepts: ['Multiple Baseline Design', 'Changing Criterion Design', 'Bidirectional Changes'],
        examWeightPercentage: 2.5,
      },
      {
        id: 'D.5',
        domainId: 'D',
        title: 'Conduct component analyses, parametric analyses, and comparative analyses',
        description: 'Isolating effective components (drop-out/add-in) and determining dosage/intensity of interventions.',
        keyConcepts: ['Component Analysis', 'Parametric Analysis', 'Comparative Analysis'],
        examWeightPercentage: 2.0,
      },
    ],
  },
  {
    id: 'E',
    name: 'Ethics',
    shortName: 'Ethics',
    description: 'Apply the BACB Ethics Code for Behavior Analysts, core ethical principles, client rights, confidentiality, conflict of interest, and assent.',
    iconName: 'ShieldCheck',
    questionCountApprox: 20,
    weightPercentage: 11,
    items: [
      {
        id: 'E.1',
        domainId: 'E',
        title: 'Apply BACB core ethical principles and code enforcement procedures',
        description: 'Benefit others, treat with compassion/dignity/respect, act with integrity, ensure competence.',
        keyConcepts: ['Core Principles', 'Ethics Code for Behavior Analysts', 'Self-Reporting'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'E.2',
        domainId: 'E',
        title: 'Responsibility in practice: client rights, consent, assent, and confidentiality',
        description: 'Obtain informed consent, respect assent/dissent, protect HIPAA/FERPA protected data.',
        keyConcepts: ['Informed Consent', 'Assent', 'Dissent', 'Confidentiality'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'E.3',
        domainId: 'E',
        title: 'Avoid multiple relationships, conflicts of interest, and exploitative practices',
        description: 'Recognize and manage dual relationships; no gifts > $10; wait 2 years post-professional relationship.',
        keyConcepts: ['Multiple Relationships', 'Gift Policy', 'Conflict of Interest'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'E.4',
        domainId: 'E',
        title: 'Maintain competence, professional development, and ethical supervision practices',
        description: 'Practice within scope of competence; provide high-quality supervision and feedback.',
        keyConcepts: ['Scope of Competence', 'Evidence-Based Supervision', 'Feedback'],
        examWeightPercentage: 2.0,
      },
    ],
  },
  {
    id: 'F',
    name: 'Behavior Assessment',
    shortName: 'Behavior Assessment',
    description: 'Conduct indirect, direct, and experimental functional assessments (FA), preference assessments, and reinforcer assessments.',
    iconName: 'ClipboardList',
    questionCountApprox: 21,
    weightPercentage: 11,
    items: [
      {
        id: 'F.1',
        domainId: 'F',
        title: 'Conduct indirect assessments, interviews, and checklists',
        description: 'FAST, MAS, QABF, and structured clinical behavioral interviews.',
        keyConcepts: ['Indirect Assessment', 'Rating Scales', 'Interviews'],
        examWeightPercentage: 2.0,
      },
      {
        id: 'F.2',
        domainId: 'F',
        title: 'Conduct direct descriptive assessments (ABC narrative and continuous recording, scatterplots)',
        description: 'Collect direct observational data in naturalistic settings without experimental manipulation.',
        keyConcepts: ['ABC Continuous', 'ABC Narrative', 'Scatterplot Analysis'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'F.3',
        domainId: 'F',
        title: 'Conduct and interpret functional analyses (analog conditions, brief FA, trial-based FA)',
        description: 'Standard analog conditions (Play/Control, Attention, Escape, Demand, Alone/Tangible); interpret multi-element FA graphs.',
        keyConcepts: ['Functional Analysis (FA)', 'Iwata Protocol', 'Brief FA', 'Trial-Based FA', 'Synthesized Contingencies (IISCA)'],
        examWeightPercentage: 4.0,
      },
      {
        id: 'F.4',
        domainId: 'F',
        title: 'Conduct preference assessments and reinforcer assessments',
        description: 'Free operant, paired choice, MSWO, MSW; concurrent, progressive-ratio, and single-operant reinforcer assessments.',
        keyConcepts: ['MSWO', 'Paired Choice', 'Progressive Ratio Reinforcer Assessment'],
        examWeightPercentage: 2.0,
      },
    ],
  },
  {
    id: 'G',
    name: 'Behavior-Change Procedures',
    shortName: 'Behavior-Change Procedures',
    description: 'Select, design, and implement reinforcement-based interventions, differential reinforcement (DRA/DRO/DRI/DRL), token economies, shaping, chaining, and extinction.',
    iconName: 'Sliders',
    questionCountApprox: 24,
    weightPercentage: 13,
    items: [
      {
        id: 'G.1',
        domainId: 'G',
        title: 'Design and implement positive and negative reinforcement procedures',
        description: 'Noncontingent reinforcement (NCR), high-probability request sequence, and differential reinforcement.',
        keyConcepts: ['NCR', 'High-P Sequence', 'Contingent Reinforcement'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'G.2',
        domainId: 'G',
        title: 'Design and implement differential reinforcement procedures (DRA, DRI, DRO, DRL, DRH)',
        description: 'DRA/DRI for functionally equivalent replacement behaviors; DRO interval calculation; DRL rate control.',
        keyConcepts: ['DRA', 'DRI', 'DRO', 'DRL', 'DRH', 'FERB'],
        examWeightPercentage: 4.0,
      },
      {
        id: 'G.3',
        domainId: 'G',
        title: 'Design and implement prompt and prompt fading procedures',
        description: 'Most-to-least, least-to-most, time delay, graduated guidance, and stimulus fading/shaping.',
        keyConcepts: ['Prompt Fading', 'Time Delay', 'Graduated Guidance', 'Stimulus Prompt Fading'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'G.4',
        domainId: 'G',
        title: 'Design and implement shaping and chaining procedures',
        description: 'Successive approximations; forward chaining, backward chaining, total-task presentation.',
        keyConcepts: ['Shaping', 'Forward Chaining', 'Backward Chaining', 'Total-Task'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'G.5',
        domainId: 'G',
        title: 'Design and implement token economies, group contingencies, and contingency contracts',
        description: 'Backup reinforcers, token exchange schedules; independent, dependent (Hero), and interdependent group contingencies.',
        keyConcepts: ['Token Economy', 'Hero Procedure', 'Interdependent Contingency', 'Contingency Contract'],
        examWeightPercentage: 3.0,
      },
      {
        id: 'G.6',
        domainId: 'G',
        title: 'Design and implement discrete-trial teaching (DTT) and naturalistic teaching (NET)',
        description: 'Structured trials with fast pacing vs child-led natural environment incidental teaching.',
        keyConcepts: ['DTT', 'NET', 'Incidental Teaching', 'Pivotal Response Training'],
        examWeightPercentage: 2.5,
      },
      {
        id: 'G.7',
        domainId: 'G',
        title: 'Design and implement functional communication training (FCT)',
        description: 'DRA variant replacing challenging behavior with functionally equivalent communicative responses.',
        keyConcepts: ['FCT', 'Communicative Replacement', 'Prompt Fading in FCT'],
        examWeightPercentage: 2.5,
      },
    ],
  },
  {
    id: 'H',
    name: 'Selecting and Implementing Interventions',
    shortName: 'Intervention Selection',
    description: 'Select socially significant intervention goals, state behavioral objectives, collaborate with stakeholders, and monitor treatment integrity.',
    iconName: 'Target',
    questionCountApprox: 13,
    weightPercentage: 7,
    items: [
      {
        id: 'H.1',
        domainId: 'H',
        title: 'Select socially valid, culturally responsive, and individualized intervention goals',
        description: 'Prioritize behavioral cusps and pivotal behaviors with consumer social validity.',
        keyConcepts: ['Social Validity', 'Behavioral Cusp', 'Pivotal Behavior', 'Cultural Responsiveness'],
        examWeightPercentage: 2.5,
      },
      {
        id: 'H.2',
        domainId: 'H',
        title: 'Plan for generalization and maintenance (train loosely, programming common stimuli)',
        description: 'Stokes & Baer (1977) generalization tactics across settings, people, and stimuli.',
        keyConcepts: ['Generalization', 'Maintenance', 'Program Common Stimuli', 'Train Loosely'],
        examWeightPercentage: 2.5,
      },
      {
        id: 'H.3',
        domainId: 'H',
        title: 'Measure and maintain treatment integrity and procedural fidelity',
        description: 'Treatment integrity monitoring checklists, IOA on independent variables, and drift prevention.',
        keyConcepts: ['Treatment Integrity', 'Procedural Fidelity', 'Treatment Drift'],
        examWeightPercentage: 2.0,
      },
    ],
  },
  {
    id: 'I',
    name: 'Personnel Supervision and Management',
    shortName: 'Supervision & Management',
    description: 'Design and implement competency-based training, performance monitoring, behaviorally anchored rating scales, feedback delivery, and OBM systems.',
    iconName: 'Users',
    questionCountApprox: 12,
    weightPercentage: 6,
    items: [
      {
        id: 'I.1',
        domainId: 'I',
        title: 'Establish clear, behavioral performance expectations and competency-based training',
        description: 'Behavioral skills training (BST: Instructions, Modeling, Rehearsal, Feedback) for supervisees and RBTs.',
        keyConcepts: ['BST (Behavioral Skills Training)', 'Competency-Based Assessment', 'Role Play'],
        examWeightPercentage: 2.0,
      },
      {
        id: 'I.2',
        domainId: 'I',
        title: 'Select and implement performance monitoring and feedback systems',
        description: 'Objective monitoring, Behaviorally Anchored Rating Scales (BARS), corrective and reinforcing feedback.',
        keyConcepts: ['Performance Monitoring', 'BARS', 'Corrective Feedback Timing', 'OBM'],
        examWeightPercentage: 2.0,
      },
      {
        id: 'I.3',
        domainId: 'I',
        title: 'Evaluate the effects of supervision and mentoring',
        description: 'Supervisory system audits, client progress correlation, and supervisee satisfaction surveys.',
        keyConcepts: ['Supervision Evaluation', 'Supervisory System Audit', 'RBT Compliance Tracking'],
        examWeightPercentage: 2.0,
      },
    ],
  },
];
