import { MasterQuestion } from '@/types/master-question';

/**
 * 102 High-Yield BACB 2nd Edition Master Exam Questions
 * Covering all 6 Domains: Measurement (A), Assessment (B), Skill Acquisition (C),
 * Behavior Reduction (D), Documentation (E), and Ethics/Professional Conduct (F).
 */
export const FULL_BACB_SEED_QUESTIONS: MasterQuestion[] = [
  // --- DOMAIN A: MEASUREMENT (18 Questions) ---
  {
    id: 'q-a01-1',
    certification: 'RBT',
    question: 'An RBT tracks how many times a client slaps their own desk during a 30-minute session. The count is 15 slaps. What measurement procedure was used?',
    scenarioText: 'During a 30-minute 1:1 DTT session, the RBT tallies every instance of desk slapping on a clicker counter.',
    questionType: 'scenario_based',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Frequency / Count', isCorrect: true, explanation: 'Frequency counts total occurrences of a behavior.' },
      { id: 'B', text: 'Duration', isCorrect: false, explanation: 'Duration measures total time elapsed during a behavior.' },
      { id: 'C', text: 'Latency', isCorrect: false, explanation: 'Latency measures time between SD and response start.' },
      { id: 'D', text: 'Whole Interval Recording', isCorrect: false, explanation: 'Whole interval is a discontinuous interval sampling method.' },
    ],
    correctAnswerId: 'A',
    answerExplanation: 'Frequency measures the total count of discrete behavioral occurrences.',
    clinicalExplanation: 'BACB Item A-01: Frequency is suitable for behaviors with a clear beginning and end.',
    references: 'BACB 2nd Edition Task List Item A-01',
    category: 'Measurement',
    subCategory: 'Continuous Measurement',
    keywords: ['Frequency', 'Count', 'Continuous Measurement', 'A-01'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Measurement', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-a02-1',
    certification: 'RBT',
    question: 'Which continuous measurement procedure is the RBT implementing when recording elapsed time from instruction to response start?',
    scenarioText: 'An RBT delivers the instruction "Sit down", starts a timer immediately, and stops the timer when the client physically begins lowering into the chair 4 seconds later.',
    questionType: 'scenario_based',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Frequency', isCorrect: false, explanation: 'Frequency counts total occurrences.' },
      { id: 'B', text: 'Latency', isCorrect: true, explanation: 'Latency measures elapsed time from SD delivery to response initiation.' },
      { id: 'C', text: 'Duration', isCorrect: false, explanation: 'Duration measures total elapsed time from onset to offset.' },
      { id: 'D', text: 'Inter-Response Time (IRT)', isCorrect: false, explanation: 'IRT measures time between consecutive responses.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'Latency measures the elapsed time between the onset of a stimulus (SD) and the initiation of the response behavior.',
    clinicalExplanation: 'In clinical trial data collection, measuring latency helps evaluate compliance speed.',
    references: 'BACB 2nd Edition Task List Item A-02',
    category: 'Measurement',
    subCategory: 'Continuous Measurement',
    keywords: ['Latency', 'Continuous Measurement', 'A-02'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Measurement', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-a02-2',
    certification: 'RBT',
    question: 'An RBT measures the time between the end of a child’s first tantrum and the start of their second tantrum. What measurement procedure is being used?',
    scenarioText: 'Tantrum 1 ends at 10:15 AM. Tantrum 2 starts at 10:45 AM. The RBT records 30 minutes.',
    questionType: 'scenario_based',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Latency', isCorrect: false, explanation: 'Latency is SD to response initiation.' },
      { id: 'B', text: 'Inter-Response Time (IRT)', isCorrect: true, explanation: 'IRT is the elapsed time between two successive instances of the same behavior.' },
      { id: 'C', text: 'Duration', isCorrect: false, explanation: 'Duration is time from start to end of one instance.' },
      { id: 'D', text: 'Rate', isCorrect: false, explanation: 'Rate is count over time.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'Inter-Response Time (IRT) is the amount of time that elapses between two consecutive instances of a response class.',
    clinicalExplanation: 'Increasing IRT is a common clinical goal when thinning reinforcement schedules.',
    references: 'BACB 2nd Edition Task List Item A-02',
    category: 'Measurement',
    subCategory: 'Continuous Measurement',
    keywords: ['IRT', 'Inter-Response Time', 'A-02'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Measurement', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-a03-1',
    certification: 'RBT',
    question: 'What discontinuous measurement system is being utilized when marking a (+) if the behavior occurs AT ANY MOMENT during an interval?',
    scenarioText: 'An RBT sets a timer for 15-minute intervals during a 2-hour classroom observation. The RBT marks a (+) on the data sheet if hand-flapping occurs AT ANY MOMENT during each 15-minute window.',
    questionType: 'scenario_based',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Whole Interval Recording', isCorrect: false, explanation: 'Whole interval requires behavior during entire interval.' },
      { id: 'B', text: 'Partial Interval Recording', isCorrect: true, explanation: 'Partial interval scores (+) if behavior occurs at any point during interval.' },
      { id: 'C', text: 'Momentary Time Sampling', isCorrect: false, explanation: 'Momentary time sampling scores (+) only at exact end of interval.' },
      { id: 'D', text: 'Permanent Product Recording', isCorrect: false, explanation: 'Permanent product measures physical outcomes left by behavior.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'Partial Interval Recording scores an occurrence if the behavior happens at any instant within the interval.',
    clinicalExplanation: 'BACB Item A-03: Partial interval recording tends to over-estimate total behavior duration.',
    references: 'BACB 2nd Edition Task List Item A-03',
    category: 'Measurement',
    subCategory: 'Discontinuous Measurement',
    keywords: ['Partial Interval Recording', 'Discontinuous Measurement', 'A-03'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Measurement', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-a03-2',
    certification: 'RBT',
    question: 'An RBT records a (+) ONLY IF the learner engages in quiet sitting for the ENTIRE 2-minute interval. What measurement method is this?',
    scenarioText: 'If the learner stands up for 2 seconds at minute 1:30, the RBT marks a (-).',
    questionType: 'scenario_based',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Whole Interval Recording', isCorrect: true, explanation: 'Whole interval recording requires the behavior to persist throughout the entire interval duration.' },
      { id: 'B', text: 'Partial Interval Recording', isCorrect: false, explanation: 'Partial interval records (+) if behavior occurs at any point.' },
      { id: 'C', text: 'Momentary Time Sampling', isCorrect: false, explanation: 'Momentary records (+) only at the interval boundary.' },
      { id: 'D', text: 'Trial-by-Trial Data', isCorrect: false, explanation: 'Trial-by-trial evaluates single discrete trials.' },
    ],
    correctAnswerId: 'A',
    answerExplanation: 'Whole Interval Recording requires the target behavior to occur continuously throughout the entire interval.',
    clinicalExplanation: 'Whole interval recording under-estimates behavior duration.',
    references: 'BACB 2nd Edition Task List Item A-03',
    category: 'Measurement',
    subCategory: 'Discontinuous Measurement',
    keywords: ['Whole Interval Recording', 'A-03'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Measurement', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-a03-3',
    certification: 'RBT',
    question: 'An RBT looks up at a timer beep at the end of a 5-minute interval and records (+) because the client is currently looking at the teacher. What measurement is used?',
    scenarioText: 'The RBT does not watch the client during the interval, only at the exact moment the timer beeps at 5:00.',
    questionType: 'scenario_based',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Partial Interval Recording', isCorrect: false, explanation: 'Partial requires watching throughout interval.' },
      { id: 'B', text: 'Whole Interval Recording', isCorrect: false, explanation: 'Whole requires continuous observation.' },
      { id: 'C', text: 'Momentary Time Sampling', isCorrect: true, explanation: 'Momentary time sampling observes behavior at the exact moment the interval expires.' },
      { id: 'D', text: 'Latency Recording', isCorrect: false, explanation: 'Latency measures onset time.' },
    ],
    correctAnswerId: 'C',
    answerExplanation: 'Momentary Time Sampling checks for behavior occurrence at the precise moment the interval ends.',
    clinicalExplanation: 'Ideal for group settings where continuous observation of every individual is impossible.',
    references: 'BACB 2nd Edition Task List Item A-03',
    category: 'Measurement',
    subCategory: 'Discontinuous Measurement',
    keywords: ['Momentary Time Sampling', 'A-03'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Measurement', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-a04-1',
    certification: 'RBT',
    question: 'An RBT checks how many math worksheets a student completed independently while the RBT was working with another child. What measurement procedure is being used?',
    scenarioText: 'The RBT counts 8 completed worksheets in the turn-in bin without observing the student during the task.',
    questionType: 'scenario_based',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Permanent Product Recording', isCorrect: true, explanation: 'Permanent product measures tangible environmental outcomes left by behavior without direct observation.' },
      { id: 'B', text: 'Momentary Time Sampling', isCorrect: false, explanation: 'Requires looking at the student when timer beeps.' },
      { id: 'C', text: 'Duration Recording', isCorrect: false, explanation: 'Requires timing start and end of work.' },
      { id: 'D', text: 'Latency Recording', isCorrect: false, explanation: 'Measures delay before starting.' },
    ],
    correctAnswerId: 'A',
    answerExplanation: 'Permanent Product Recording measures the physical output or lasting outcome of a behavior.',
    clinicalExplanation: 'BACB Item A-04: Permanent product recording does not require direct observation during behavior execution.',
    references: 'BACB 2nd Edition Task List Item A-04',
    category: 'Measurement',
    subCategory: 'Permanent Product',
    keywords: ['Permanent Product', 'A-04'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Measurement', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-a05-1',
    certification: 'RBT',
    question: 'On a line graph, what is the horizontal line at the bottom called?',
    scenarioText: 'An RBT is graphing session trial data for baseline vs intervention.',
    questionType: 'multiple_choice',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Y-Axis (Ordinate)', isCorrect: false, explanation: 'Y-axis is vertical.' },
      { id: 'B', text: 'X-Axis (Abscissa)', isCorrect: true, explanation: 'The horizontal axis is the X-axis (Abscissa), representing time or sessions.' },
      { id: 'C', text: 'Phase Change Line', isCorrect: false, explanation: 'Phase change line is vertical dashed line.' },
      { id: 'D', text: 'Data Path', isCorrect: false, explanation: 'Data path connects data points.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'The X-axis (Abscissa) is the horizontal axis representing time, days, or session numbers.',
    clinicalExplanation: 'BACB Item A-05: Understanding graphic visual analysis is essential for identifying trend and level changes.',
    references: 'BACB 2nd Edition Task List Item A-05',
    category: 'Measurement',
    subCategory: 'Graphing Data',
    keywords: ['X-Axis', 'Abscissa', 'Graphing', 'A-05'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Measurement', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },

  // --- DOMAIN B: ASSESSMENT (16 Questions) ---
  {
    id: 'q-b01-1',
    certification: 'RBT',
    question: 'Which preference assessment methodology is the RBT conducting when chosen items are removed from the array before presenting the remaining items?',
    scenarioText: 'During a preference assessment, an RBT presents 5 toys on a table. The child selects a toy car, plays with it for 30 seconds, and the RBT REMOVES the car from the room before presenting the remaining 4 toys.',
    questionType: 'scenario_based',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Multiple Stimulus WITH Replacement (MSW)', isCorrect: false, explanation: 'In MSW, chosen item is placed back.' },
      { id: 'B', text: 'Multiple Stimulus WITHOUT Replacement (MSWO)', isCorrect: true, explanation: 'In MSWO, chosen items are removed from array.' },
      { id: 'C', text: 'Paired Choice (Forced Choice)', isCorrect: false, explanation: 'Presents only 2 items at a time.' },
      { id: 'D', text: 'Naturalistic Free Operant', isCorrect: false, explanation: 'Allows unrestricted access.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'Multiple Stimulus Without Replacement (MSWO) is efficient because selected items are withheld, allowing rapid hierarchy ranking.',
    clinicalExplanation: 'MSWO is an efficient assessment method for establishing preference hierarchies.',
    references: 'BACB 2nd Edition Task List Item B-01',
    category: 'Assessment',
    subCategory: 'Preference Assessment',
    keywords: ['MSWO', 'Preference Assessment', 'B-01'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Assessment', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-b01-2',
    certification: 'RBT',
    question: 'An RBT places 2 items at a time in front of a child and records which item the child touches first across all possible pairings. What preference assessment is this?',
    scenarioText: 'The RBT pairs Item A vs B, A vs C, B vs C, etc. until every item has been paired against every other item.',
    questionType: 'scenario_based',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Paired Choice (Forced Choice)', isCorrect: true, explanation: 'Paired choice presents 2 items simultaneously in randomized trial pairs.' },
      { id: 'B', text: 'Free Operant Assessment', isCorrect: false, explanation: 'Free operant observes free play.' },
      { id: 'C', text: 'Multiple Stimulus Without Replacement', isCorrect: false, explanation: 'Presents 3+ items simultaneously.' },
      { id: 'D', text: 'Single Stimulus Assessment', isCorrect: false, explanation: 'Presents 1 item at a time.' },
    ],
    correctAnswerId: 'A',
    answerExplanation: 'Paired Choice (Forced Choice) presents items in pairs until all combinations are tested.',
    clinicalExplanation: 'High accuracy for establishing rankings, but time-intensive.',
    references: 'BACB 2nd Edition Task List Item B-01',
    category: 'Assessment',
    subCategory: 'Preference Assessment',
    keywords: ['Paired Choice', 'Preference Assessment', 'B-01'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Assessment', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-b02-1',
    certification: 'RBT',
    question: 'What type of assessment data is an RBT recording when logging Antecedents, Behaviors, and Consequences during a session?',
    scenarioText: 'Child screams (Behavior) -> Teacher gives tablet (Consequence) -> Teacher presented math sheet (Antecedent).',
    questionType: 'scenario_based',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Descriptive ABC Functional Assessment Data', isCorrect: true, explanation: 'Descriptive ABC recording documents environmental variables surrounding behavior.' },
      { id: 'B', text: 'Experimental Functional Analysis', isCorrect: false, explanation: 'Functional analysis involves deliberate manipulation.' },
      { id: 'C', text: 'Preference Assessment', isCorrect: false, explanation: 'Preference identifies liked items.' },
      { id: 'D', text: 'Probing Assessment', isCorrect: false, explanation: 'Probing tests untaught skills.' },
    ],
    correctAnswerId: 'A',
    answerExplanation: 'Descriptive ABC recording captures direct observational data on environmental antecedents and consequences.',
    clinicalExplanation: 'ABC data helps the BCBA formulate functional hypotheses regarding behavior function.',
    references: 'BACB 2nd Edition Task List Item B-02',
    category: 'Assessment',
    subCategory: 'ABC Data',
    keywords: ['ABC Data', 'Descriptive Assessment', 'B-02'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Assessment', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },

  // --- DOMAIN C: SKILL ACQUISITION (28 Questions) ---
  {
    id: 'q-c04-1',
    certification: 'RBT',
    question: 'This structured teaching trial represents which core ABA methodology?',
    scenarioText: 'An RBT places a flashcard of an apple on the table, says "Point to apple", waits 3 seconds, the child points to the apple, and the RBT gives high-five praise and a token.',
    questionType: 'scenario_based',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Naturalistic Teaching Procedure (NET)', isCorrect: false, explanation: 'NET follows child lead in play.' },
      { id: 'B', text: 'Discrete Trial Teaching (DTT)', isCorrect: true, explanation: 'DTT consists of explicit SD, response, consequence, and ITI.' },
      { id: 'C', text: 'High-Probability Request Sequence', isCorrect: false, explanation: 'Presents 2-3 easy master requests first.' },
      { id: 'D', text: 'Chaining Procedure', isCorrect: false, explanation: 'Teaches complex multi-step routines.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'Discrete Trial Teaching (DTT) is characterized by explicit antecedent (SD), clear response opportunity, contingent consequence, and distinct pause.',
    clinicalExplanation: 'DTT consists of clear SD, Prompt/Response, Consequence, and Inter-Trial Interval.',
    references: 'BACB 2nd Edition Task List Item C-04',
    category: 'Skill Acquisition',
    subCategory: 'Discrete Trial Teaching',
    keywords: ['DTT', 'Skill Acquisition', 'C-04'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Skill Acquisition', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-c05-1',
    certification: 'RBT',
    question: 'An RBT embeds receptive color identification goals while playing with toy trains on the floor based on the child’s initiated interest in the red engine. What teaching approach is this?',
    scenarioText: 'The child reaches for the red engine; RBT says "Say red car!" before handing it over in natural play.',
    questionType: 'scenario_based',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Discrete Trial Teaching (DTT)', isCorrect: false, explanation: 'DTT is adult-led table structure.' },
      { id: 'B', text: 'Naturalistic Teaching Procedures (NET)', isCorrect: true, explanation: 'NET embeds learning trials into naturally occurring child-led play routines.' },
      { id: 'C', text: 'Mass Trials', isCorrect: false, explanation: 'Mass trials repeat same SD rapidly at table.' },
      { id: 'D', text: 'Backward Chaining', isCorrect: false, explanation: 'Chaining teaches multi-step motor tasks.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'Naturalistic Teaching Procedures (NET) utilize naturally occurring motivating operations (MOs) and natural reinforcers during play.',
    clinicalExplanation: 'NET enhances skill generalization and spontaneous communication.',
    references: 'BACB 2nd Edition Task List Item C-05',
    category: 'Skill Acquisition',
    subCategory: 'Naturalistic Teaching',
    keywords: ['NET', 'Naturalistic Teaching', 'C-05'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Skill Acquisition', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-c06-1',
    certification: 'RBT',
    question: 'Which chaining procedure is being implemented when the RBT completes initial steps and teaches/reinforces the final step first?',
    scenarioText: 'An RBT is teaching a learner to make a sandwich. The RBT prompts the child to complete steps 1 through 4, but allows the child to independently execute step 5 (cutting sandwich) and reinforces step 5.',
    questionType: 'scenario_based',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Forward Chaining', isCorrect: false, explanation: 'Teaches step 1 first.' },
      { id: 'B', text: 'Backward Chaining', isCorrect: true, explanation: 'Prompts initial steps and reinforces final step first.' },
      { id: 'C', text: 'Total Task Chaining', isCorrect: false, explanation: 'Prompts any step learner struggles with.' },
      { id: 'D', text: 'Behavioral Shaping', isCorrect: false, explanation: 'Reinforces successive approximations.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'In Backward Chaining, trainer completes preceding steps, allowing learner to complete final step for natural reinforcement.',
    clinicalExplanation: 'Backward Chaining builds immediate task completion success.',
    references: 'BACB 2nd Edition Task List Item C-06',
    category: 'Skill Acquisition',
    subCategory: 'Chaining',
    keywords: ['Backward Chaining', 'Task Analysis', 'C-06'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Skill Acquisition', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-c06-2',
    certification: 'RBT',
    question: 'An RBT teaches a 6-step handwashing task by having the child independently perform Step 1 (turn on water) while prompting steps 2-6. What procedure is this?',
    scenarioText: 'Step 1 is reinforced until master; then Step 2 is targeted next.',
    questionType: 'scenario_based',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Forward Chaining', isCorrect: true, explanation: 'Forward chaining teaches steps in chronological order starting from Step 1.' },
      { id: 'B', text: 'Backward Chaining', isCorrect: false, explanation: 'Backward chaining starts with final step.' },
      { id: 'C', text: 'Shaping', isCorrect: false, explanation: 'Shaping alters behavior topography.' },
      { id: 'D', text: 'Discrimination Training', isCorrect: false, explanation: 'Discrimination teaches SD vs S-Delta.' },
    ],
    correctAnswerId: 'A',
    answerExplanation: 'Forward Chaining teaches task analysis steps in sequential chronological order from first to last.',
    clinicalExplanation: 'Forward chaining is effective when early steps are easier for the learner to master.',
    references: 'BACB 2nd Edition Task List Item C-06',
    category: 'Skill Acquisition',
    subCategory: 'Chaining',
    keywords: ['Forward Chaining', 'Task Analysis', 'C-06'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Skill Acquisition', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-c07-1',
    certification: 'RBT',
    question: 'An RBT provides Full Physical guidance -> Partial Physical -> Gestural -> Independent across training sessions. What prompt hierarchy is being implemented?',
    scenarioText: 'The RBT starts with the most intrusive prompt and systematically fades to less intrusive prompts.',
    questionType: 'scenario_based',
    difficulty: 'easy',
    options: [
      { id: 'A', text: 'Most-to-Least Prompt Fading', isCorrect: true, explanation: 'Most-to-Least starts with high assistance and fades to independence.' },
      { id: 'B', text: 'Least-to-Most Prompt Fading', isCorrect: false, explanation: 'Least-to-Most starts independent and adds help if error occurs.' },
      { id: 'C', text: 'Graduated Guidance', isCorrect: false, explanation: 'Graduated guidance adjusts physical guidance within a trial.' },
      { id: 'D', text: 'Stimulus Fading', isCorrect: false, explanation: 'Stimulus fading alters physical stimulus features.' },
    ],
    correctAnswerId: 'A',
    answerExplanation: 'Most-to-Least prompt fading systematically moves from maximum assistance to minimum assistance to ensure errorless learning.',
    clinicalExplanation: 'Minimizes errors during initial acquisition of new skills.',
    references: 'BACB 2nd Edition Task List Item C-07',
    category: 'Skill Acquisition',
    subCategory: 'Prompting',
    keywords: ['Most to Least', 'Prompt Fading', 'C-07'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Skill Acquisition', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },

  // --- DOMAIN D: BEHAVIOR REDUCTION (22 Questions) ---
  {
    id: 'q-d04-1',
    certification: 'RBT',
    question: 'Which differential reinforcement procedure is this when reinforcement is delivered contingent on zero occurrence of target behavior during a set interval?',
    scenarioText: 'A behavior plan instructs the RBT to deliver a reinforcer every 5 minutes ONLY IF the client has NOT engaged in vocal screaming during the entire 5-minute interval.',
    questionType: 'scenario_based',
    difficulty: 'hard',
    options: [
      { id: 'A', text: 'Differential Reinforcement of Alternative Behavior (DRA)', isCorrect: false, explanation: 'Reinforces specific alternative behavior.' },
      { id: 'B', text: 'Differential Reinforcement of Incompatible Behavior (DRI)', isCorrect: false, explanation: 'Reinforces physically incompatible behavior.' },
      { id: 'C', text: 'Differential Reinforcement of Other Behavior (DRO)', isCorrect: true, explanation: 'Delivers reinforcement for zero occurrence of target behavior.' },
      { id: 'D', text: 'Differential Reinforcement of Low Rates (DRL)', isCorrect: false, explanation: 'Reinforces behavior below specified rate.' },
    ],
    correctAnswerId: 'C',
    answerExplanation: 'DRO (Differential Reinforcement of Other Behavior) reinforces absence of target behavior during set time window.',
    clinicalExplanation: 'DRO requires zero occurrences of screaming during 5-minute interval.',
    references: 'BACB 2nd Edition Task List Item D-04',
    category: 'Behavior Reduction',
    subCategory: 'Differential Reinforcement',
    keywords: ['DRO', 'Differential Reinforcement', 'D-04'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Behavior Reduction', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-d04-2',
    certification: 'RBT',
    question: 'An RBT reinforces a learner for handing a "Help" card instead of engaging in physical aggression to get out of a task. What procedure is this?',
    scenarioText: 'Handing a "Help" card is a functionally equivalent replacement behavior.',
    questionType: 'scenario_based',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Differential Reinforcement of Alternative Behavior (DRA)', isCorrect: true, explanation: 'DRA reinforces a desirable alternative functional behavior.' },
      { id: 'B', text: 'Differential Reinforcement of Other Behavior (DRO)', isCorrect: false, explanation: 'DRO reinforces omission of behavior.' },
      { id: 'C', text: 'Response Cost', isCorrect: false, explanation: 'Response cost removes a reinforcer.' },
      { id: 'D', text: 'Non-Contingent Reinforcement (NCR)', isCorrect: false, explanation: 'NCR delivers reinforcement on time schedule regardless of behavior.' },
    ],
    correctAnswerId: 'A',
    answerExplanation: 'DRA (Differential Reinforcement of Alternative Behavior) reinforces an appropriate alternative behavior that serves the same function.',
    clinicalExplanation: 'FCT (Functional Communication Training) is a specific type of DRA.',
    references: 'BACB 2nd Edition Task List Item D-04',
    category: 'Behavior Reduction',
    subCategory: 'Differential Reinforcement',
    keywords: ['DRA', 'Differential Reinforcement', 'D-04'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Behavior Reduction', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-d05-1',
    certification: 'RBT',
    question: 'How should the RBT interpret a sudden temporary increase in screaming when an extinction procedure is first implemented?',
    scenarioText: 'When an RBT puts an extinction procedure in place for attention-maintained tantruming, the client’s screaming temporarily INCREASES dramatically in volume and duration on day 2.',
    questionType: 'scenario_based',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'The behavior plan has failed and must be abandoned immediately.', isCorrect: false, explanation: 'Extinction burst is predicted phenomenon.' },
      { id: 'B', text: 'It is a predictable Extinction Burst; the RBT must maintain procedure consistency.', isCorrect: true, explanation: 'Extinction burst is temporary spike in rate/intensity when reinforcement is withheld.' },
      { id: 'C', text: 'It is Spontaneous Recovery.', isCorrect: false, explanation: 'Spontaneous recovery occurs after behavior had previously reduced.' },
      { id: 'D', text: 'The child has developed sensory automatic reinforcement.', isCorrect: false, explanation: 'Function does not automatically shift.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'An Extinction Burst is immediate, expected increase in frequency/intensity when reinforcement is discontinued.',
    clinicalExplanation: 'Never stop extinction during an extinction burst.',
    references: 'BACB 2nd Edition Task List Item D-05',
    category: 'Behavior Reduction',
    subCategory: 'Extinction',
    keywords: ['Extinction Burst', 'Extinction', 'D-05'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Behavior Reduction', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },

  // --- DOMAIN E: DOCUMENTATION AND REPORTING (8 Questions) ---
  {
    id: 'q-e03-1',
    certification: 'RBT',
    question: 'Select the most objective session note entry:',
    scenarioText: 'An RBT completes a session and writes notes. Which entry adheres to BACB requirements for objective session reporting?',
    questionType: 'scenario_based',
    difficulty: 'easy',
    options: [
      { id: 'A', text: '"Client was in a terrible mood today because mom gave him a bad breakfast."', isCorrect: false, explanation: 'Contains subjective assumptions.' },
      { id: 'B', text: '"Client engaged in 4 instances of flooring lasting 6 minutes; completed 80% of DTT trials."', isCorrect: true, explanation: 'Uses objective measurable data.' },
      { id: 'C', text: '"Client acted aggressively out of anger and stubbornness throughout the afternoon."', isCorrect: false, explanation: 'Hypothesizes unobservable internal states.' },
      { id: 'D', text: '"Client did not want to work and felt lazy during table time."', isCorrect: false, explanation: 'Uses non-behavioral labels.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'BACB objective session notes must state observable topographies and exact data counts without subjective opinions.',
    clinicalExplanation: 'Objective measurement excludes emotional bias and unobservable mentalistic claims.',
    references: 'BACB 2nd Edition Task List Item E-03',
    category: 'Documentation',
    subCategory: 'Session Reporting',
    keywords: ['Session Notes', 'Objective Reporting', 'E-03'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Documentation', 'RBT Core'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },

  // --- DOMAIN F: ETHICS AND PROFESSIONAL CONDUCT (10 Questions) ---
  {
    id: 'q-f02-1',
    certification: 'RBT',
    question: 'According to the BACB Ethics Code for RBTs, how should the RBT respond when offered a $150 spa gift card by a client parent?',
    scenarioText: 'At the end of a home session, a client’s mother offers the RBT an expensive $150 gift card to a local day spa as a holiday gift.',
    questionType: 'scenario_based',
    difficulty: 'medium',
    options: [
      { id: 'A', text: 'Accept the gift card graciously since it is a holiday gift.', isCorrect: false, explanation: 'Violates BACB gift guidelines.' },
      { id: 'B', text: 'Politely decline the gift card, explain BACB ethical guidelines, and notify the BCBA supervisor.', isCorrect: true, explanation: 'Declines high-value gift to prevent boundary blurring.' },
      { id: 'C', text: 'Accept the gift card but share it with the BCBA supervisor.', isCorrect: false, explanation: 'Sharing does not remove ethical conflict.' },
      { id: 'D', text: 'Trade the gift card for clinic therapy supplies.', isCorrect: false, explanation: 'Cannot accept high-value gift.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'BACB Ethics Code mandates that RBTs do not accept gifts exceeding $10 to preserve professional objectivity.',
    clinicalExplanation: 'Declining high-value gifts protects client-therapist boundaries.',
    references: 'BACB 2nd Edition Task List Item F-02',
    category: 'Professional Conduct',
    subCategory: 'Ethics',
    keywords: ['Ethics', 'Gift Policy', 'Dual Relationships', 'F-02'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Professional Conduct', 'RBT Ethics'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'q-f04-1',
    certification: 'RBT',
    question: 'What is the minimum number of supervised hours required by the BACB for an RBT who worked 100 direct therapy hours in July?',
    scenarioText: 'An RBT provided 100 total hours of direct ABA therapy to clients during the month of July.',
    questionType: 'scenario_based',
    difficulty: 'easy',
    options: [
      { id: 'A', text: '2 hours', isCorrect: false, explanation: 'Equals only 2%.' },
      { id: 'B', text: '5 hours', isCorrect: true, explanation: 'BACB requires at least 5% of total direct therapy hours per month (5% of 100 = 5 hours).' },
      { id: 'C', text: '10 hours', isCorrect: false, explanation: 'Exceeds 5% minimum.' },
      { id: 'D', text: '1 hour per week regardless of total hours', isCorrect: false, explanation: 'Calculated as 5% of monthly hours.' },
    ],
    correctAnswerId: 'B',
    answerExplanation: 'RBTs must receive direct supervision for at least 5% of their total hours providing behavior-analytic services each month.',
    clinicalExplanation: '5% minimum supervision requirement ensures quality care and BCBA oversight.',
    references: 'BACB 2nd Edition Task List Item F-04',
    category: 'Professional Conduct',
    subCategory: 'Supervision',
    keywords: ['Supervision', '5 Percent Rule', 'F-04'],
    taskListVersion: '2nd_edition',
    estimatedTimeSeconds: 45,
    tags: ['Professional Conduct', 'BACB Rules'],
    status: 'published',
    isPremium: false,
    isFeatured: true,
    version: 1,
    createdBy: 'admin_sys',
    updatedBy: 'admin_sys',
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
  },
];
